### PR TITLE
Read emails from local md

### PR DESCRIPTION
**Pull request by CristinaRuth**
Updated to read emails from local markdown files and to read event data from the spreadsheet, and updated corresponding readme.md for documentation.

Other Changes:

- renamed variable names for more clarity.
- updated function name whose functionality was changed to indicate event data is also being replaced.

### CODE REVIEW

**Comment by CristinaRuth** [comment]
Hi Mercedes,

I added this update in - I hope it looks fine.  The ghost emoji wasn't compatible with the update but I did find an HTML entity for it so it still shows up in the mentee email.

My thinking was that:

1. We would have email data in source control. We can then update it as we want before running the mailer.
2. Less manual work for us since we do not have to copy/paste email data into the spreadsheet every time.
3. Automatically generating event data in the email would mean less manual work for us.
4. Should we want to have separate emails for each chapter, I can make modifications, but I left it non-chapter specific for now to keep it simple.


Thanks,
Cristina

**Comment by mercedesb** [comment]
Hi Cristina,

I really like the idea of adding event details as configuration, that's great. 

I hear you about not copy/pasting emails into Google Sheets. However, I would prefer not to have markdown read from local files. My thought process is that by having the markdown as part of the Google Sheet, all data and communication for the event is in one location for reference in the future. I don't send the same emails every month and like having one document to reference if I need to rather than trying to dig through Github to see what I sent in July.

And I'd prefer that email files do not get checked into source control since we're both using this repo and will not be sending the same emails. 

That being said I'm so glad you found a way to make your workflow easier! I won't be merging this into master but that doesn't stop you from maintaining your branch 😄

Thanks!
Mercedes

**Comment by CristinaRuth** [comment]
Gotcha - thanks for explaining your thought process. Keeping the email details in the spreadsheet makes sense. 

I will keep this as a copy for me so I can use it in the future! Now that you mentioned being able to see the email sent in the spreadsheet, I may update such that it writes the email used to the spreadsheet if possible.

**Comment by CristinaRuth** [comment]
I made updates so it writes the emails to the spreadsheet now. I'll keep it in my fork, but in case you ever want it in the future, let me know :)

**Comment by mercedesb** [comment]
I think that's a great idea! 

If we .gitignore the email markdown files so we each can maintain our own copies, I'd like to merge that in. Open that PR :)

**Comment by CristinaRuth** [comment]
Nice! Will update shortly - this is great too for future chapters - each one can have their own copies. Awesome!

**Comment by CristinaRuth** [comment]
Second thought, I have to get going to work - I'll work on this tonight :)

**Comment by CristinaRuth** [comment]
@mercedesb Ready for your review. I did keep the "sample" emails in there, with instructions to copy them and rename them to the actual file names that are used for the emails. Those ones are git-ignored so they won't get into the repo.

Let me know if you want to change some things.

**Pull request merged**
